/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.jimmy.android;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icq_offline=0x7f020000;
        public static final int icq_online=0x7f020001;
        public static final int jabber_offline=0x7f020002;
        public static final int jabber_online=0x7f020003;
        public static final int jimmyim_splash=0x7f020004;
        public static final int jimmyim_splash_small=0x7f020005;
        public static final int jimmyim_splash_trans=0x7f020006;
        public static final int msn_offline=0x7f020007;
        public static final int msn_online=0x7f020008;
        public static final int yahoo_challenge=0x7f020009;
        public static final int yahoo_offline=0x7f02000a;
        public static final int yahoo_online=0x7f02000b;
    }
    public static final class id {
        public static final int auto_conn_text=0x7f050011;
        public static final int auto_connect=0x7f050010;
        public static final int icq=0x7f050004;
        public static final int jabber=0x7f050005;
        public static final int msn=0x7f050006;
        public static final int name=0x7f050001;
        public static final int name_text=0x7f050000;
        public static final int new_acc_accept=0x7f050013;
        public static final int new_acc_discard=0x7f050015;
        public static final int password=0x7f05000b;
        public static final int password_text=0x7f05000a;
        public static final int port=0x7f05000f;
        public static final int port_text=0x7f05000e;
        public static final int protocol_text=0x7f050002;
        public static final int protocols=0x7f050003;
        public static final int server=0x7f05000d;
        public static final int server_text=0x7f05000c;
        public static final int ssl=0x7f050012;
        public static final int ssl_text=0x7f050014;
        public static final int username=0x7f050009;
        public static final int username_text=0x7f050008;
        public static final int yahoo=0x7f050007;
    }
    public static final class layout {
        public static final int new_account=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int button_accept=0x7f040001;
        public static final int button_decline=0x7f040002;
        public static final int menu_acc_delete=0x7f040006;
        public static final int menu_acc_edit=0x7f040007;
        public static final int menu_acc_login=0x7f040008;
        public static final int menu_acc_logout=0x7f040009;
        public static final int menu_acc_new=0x7f040005;
        public static final int menu_acc_roster=0x7f04000a;
        public static final int new_acc_auto_conn=0x7f040015;
        public static final int new_acc_name=0x7f040010;
        public static final int new_acc_pass=0x7f040012;
        public static final int new_acc_port=0x7f040014;
        public static final int new_acc_proto_icq=0x7f04000c;
        public static final int new_acc_proto_jabber=0x7f04000e;
        public static final int new_acc_proto_msn=0x7f04000d;
        public static final int new_acc_proto_yahoo=0x7f04000f;
        public static final int new_acc_protocol=0x7f04000b;
        public static final int new_acc_server=0x7f040013;
        public static final int new_acc_ssl=0x7f040016;
        public static final int new_acc_username=0x7f040011;
        public static final int title_create_account=0x7f040003;
        public static final int title_edit_account=0x7f040004;
    }
}
